### ISSUE TITLE
Please add - SANS Internet Storm Center's intelfeed

### ISSUE THREAD

**Issue by presianbg** [CriticalPathSecurity/Zeek-Intelligence-Feeds#10]
Hi,

**First of all thanks for the awesome repo and the daily feed updates!**

Since you are doing the collection, normalization and transformation of the feeds in the background (not part of this repo), 
I have no idea how to contribute via a PR. 

Would you consider including the following feed:
https://isc.sans.edu/api/intelfeed

More info:
https://isc.sans.edu/api/
https://isc.sans.edu/forums/diary/Updates+to+Our+DatafeedsAPI/27824

Let me know if I can help you somehow.

Cheers,
PY

**Comment by Patrick-Kelley** [comment]
Does this get you what you're looking for?

https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/master/sans.intel

**Comment by presianbg** [comment]
Thank you, @Patrick-Kelley !

**Comment by Patrick-Kelley** [comment]
Added and closed.
