### ISSUE TITLE
You have a False Positive by adding Google's IP 8.8.8.8 to your cps-collected-iocs.intel feed

### ISSUE THREAD

**Issue by eldraco** [CriticalPathSecurity/Zeek-Intelligence-Feeds#11]
Updated on 2022/03/05

grep 8.8.8.8 cps-collected-iocs.intel
8.8.8.8	Intel::ADDR	Conti	F	Conti

Please delete. Thanks

**Comment by Patrick-Kelley** [comment]
Removed!

Thank you for the assist!
