### ISSUE TITLE
False positive cps_cobaltstrike_domain.intel

### ISSUE THREAD

**Issue by lvjurz** [CriticalPathSecurity/Zeek-Intelligence-Feeds#12]
Hi, cps_cobaltstrike_domain.intel contains domains such as
"seen.indicator":"code.jquery.com"
"seen.indicator":"outlook.live.com"
"seen.indicator":"www.adobe.com"
"seen.indicator":"www.bing.com"
"seen.indicator":"www.microsoft.com"

which all seem legitimate domains, please remove.

**Comment by Patrick-Kelley** [comment]
Will do! Seems to be an issue with the upstream source, but I can filter them out of this repository.

**Comment by Patrick-Kelley** [comment]
False positives are removed!  Thank you @lvjurz for sending this over.
