### ISSUE TITLE
Invalid IP in abuse-ch-threatfox

### ISSUE THREAD

**Issue by mgcdeltarisk** [CriticalPathSecurity/Zeek-Intelligence-Feeds#16]
This is an invalid IP: https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/master/abuse-ch-threatfox-ip.intel#L18

**Comment by Patrick-Kelley** [comment]
Working on a filter routine for the Abuse-CH feeds now.

**Comment by Patrick-Kelley** [comment]
The invalid IP of "143.404.146.87" is part of the source feed from Abuse-CH.  However, it has been removed and will be filtered as we continue to pull the Threatfox feed each hour. Thank you for letting me know!
