### ISSUE TITLE
Invalid IP Address in abuse-ch-threatfox-ip.intel line #36

### ISSUE THREAD

**Issue by hgwheels** [CriticalPathSecurity/Zeek-Intelligence-Feeds#17]
https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/180033204de1e028b681b8cc5b5429f80a19e7b9/abuse-ch-threatfox-ip.intel#L36

**Comment by Patrick-Kelley** [comment]
Working on a filter routine for the Abuse-CH feeds now.

**Comment by Patrick-Kelley** [comment]
The invalid IP of "143.404.146.87" is part of the source feed from Abuse-CH.  However, it has been removed and will be filtered as we continue to pull the Threatfox feed each hour. Thank you for letting me know!
