### ISSUE TITLE
[Issue] Empty feed dom-bl.intel

### ISSUE THREAD

**Issue by AlyaGomaa** [CriticalPathSecurity/Zeek-Intelligence-Feeds#19]
Hello we're using this feed in our Slips (Stratosphere Linux IPS) IPS.
https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/master/dom-bl.intel 
This feed is now empty. 
is it empty on purpose?
if so are you planning to fill it with IoCs any soon?
Thanks

**Comment by Patrick-Kelley** [comment]
Yes. Let me see what happened with the upstream provider.

**Comment by Patrick-Kelley** [comment]
The provider has removed this feed. For the moment, it will be removed from the repo. I will look for other options.

**Comment by AlyaGomaa** [comment]
ok thanks.
