### ISSUE TITLE
/opt/zeek/auxil/libkqueue/src/common/debug.c:1: fatal error: opening dependency file CMakeFiles/objlib.dir/src/common/debug.c.o.d: Permission denied

### ISSUE THREAD

**Issue by qasidali861** [CriticalPathSecurity/Zeek-Intelligence-Feeds#21]
I am getting this error while installing zeek?
Any lead due to what issues it's giving me error

**Comment by Patrick-Kelley** [comment]
For Zeek installation issues, I would recommend asking them over at the Zeek GitHub Repository. 

https://github.com/zeek/zeek
