### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by Niloooooooooo** [CriticalPathSecurity/Zeek-Intelligence-Feeds#23]
Hello, I have found  [www.youtube.com](http://www.youtube.com/) being flagged as drb_ra_domains . Is it false positive? Thanks
source in: [drb_ra_domain.intel](https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/master/drb_ra_domain.intel)

www.youtube.com	Intel::DOMAIN	DRB-RA	F	C2

**Comment by Patrick-Kelley** [comment]
I'll remove it, immediately. I'll also work with the upstream provider to have it removed.

**Comment by Niloooooooooo** [comment]
Thanks for your help

**Comment by Patrick-Kelley** [comment]
You are most welcome! The removal should be in this next batch.

Reopening the ticket until I confirm resolution.

**Comment by Patrick-Kelley** [comment]
Issue confirmed as resolved. Thank you for reporting the issue!
