### ISSUE TITLE
How to set meta.do-notice to T for all feeds?

### ISSUE THREAD

**Issue by DkYSwe** [CriticalPathSecurity/Zeek-Intelligence-Feeds#25]
Stumbled over this great repo with your great work being put into it.

Is there any easy way when downloading the feeds to have meta.do-notice set to T for all indicators?

Would be great if there's a simple clean way - if yes - it would be great if the documentation could cover it in some lines.

Best Regards,
Daniel

**Comment by Patrick-Kelley** [comment]
I'll work on that for you, today!

**Comment by DkYSwe** [comment]
Sounds great!  
Maybe it would be great to be able to set notice indicator in some additional file so a complete intel source can be setup to notice or not. :)

**Comment by Patrick-Kelley** [comment]
Here you go! I built a quick python script for you.

https://github.com/CriticalPathSecurity/turbo-parakeet

Adjust as you need. If you have some changes or improvements, feel free to do a pull request. 

In Zeek, load this path for you threat intelligence:
"/usr/local/zeek/share/zeek/site/Zeek-Intelligence-Feeds-Modified"

If this is satisfactory, feel free to close the ticket.

**Comment by DkYSwe** [comment]
Great  work and thanks Patrick! :)

A small bug, was found I assume, parts[4] = "T" should be [3] but worked just fine after that change.

**Comment by Patrick-Kelley** [comment]
Indeed! Updated and committed. 

Thank you, @DkYSwe!
