### ISSUE TITLE
JA3 entries have incorrect indicator_type

### ISSUE THREAD

**Issue by JustinAzoff** [CriticalPathSecurity/Zeek-Intelligence-Feeds#26]
Hi,

The indicator_type in JA3 entires is `Intel::IN_JA3` but it should be `Intel::JA3`.

This causes errors and the entries to be ignored:

```
warning: Value 'Intel::IN_JA3' for stream 'intel-/intel-1.dat' is not a valid enum.
warning: Value 'Intel::IN_JA3' for stream 'intel-/intel-1.dat' is not a valid enum.
warning: Value 'Intel::IN_JA3' for stream 'intel-/intel-1.dat' is not a valid enum.
...
```

**Comment by Patrick-Kelley** [comment]
Resolving now. 

Thank you, @JustinAzoff!

**Comment by Patrick-Kelley** [comment]
@JustinAzoff - the change has been made in the feed generation process and an off-schedule job is running right now.

**Comment by Patrick-Kelley** [comment]
@JustinAzoff - all instances are updated and the workflow changed. This issue should be resolved going forward. 

I greatly appreciate your letting me know of this issue.
