### ISSUE TITLE
Invalid IP address in tweetfeed.intel

### ISSUE THREAD

**Issue by mgcdeltarisk** [CriticalPathSecurity/Zeek-Intelligence-Feeds#27]
https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/dde92f8569eabb4fe6ce08e1c37c1a79ffdf31b8/tweetfeed.intel#L1224

This IP is invalid due to the last octet.

**Comment by Patrick-Kelley** [comment]
Copy. I've notified the upstream provider for this feed. 

Additionally, the IP will be filtered from future Zeek feed builds. I'm running a one-off process job, now.

Thank you for letting me know!

**Comment by mgcdeltarisk** [comment]
Thanks Patrick!

**Comment by Patrick-Kelley** [comment]
You are most welcome!
