### ISSUE TITLE
Invalid IP in tweetfeed.intel

### ISSUE THREAD

**Issue by mgcdeltarisk** [CriticalPathSecurity/Zeek-Intelligence-Feeds#29]
Hello, there is an invalid IP address in the tweetfeed.intel file here: https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/37f5bbcaae6e2d5d926050125cbd0b52e6e53e81/tweetfeed.intel#L1045

This IP is invalid due to the last octet. Thanks!

**Comment by Patrick-Kelley** [comment]
I'll work on this now!

**Comment by Patrick-Kelley** [comment]
Removed. 

As always, THANK YOU! I appreciate the assistance in maintaining these feeds, even against errors from the upstream provider.

**Comment by mgcdeltarisk** [comment]
Thanks Patrick!
