### ISSUE TITLE
Weird hash marked as domain in cps-collected-iocs.intel

### ISSUE THREAD

**Issue by AlyaGomaa** [CriticalPathSecurity/Zeek-Intelligence-Feeds#30]
Hello, 

I'm working on Slips IDS and it's consuming the  ```cps-collected-iocs.intel``` feed from the master branch
https://raw.githubusercontent.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/master/cps-collected-iocs.intel

it's complaining about this line
22813a7723dbdceb828c0263431465e3698aa0fc	Intel::DOMAIN	CPS-CTI	F	PHISHING

I'm not sure what kind of hash this is, and why is it marked as DOMAIN

**Comment by Patrick-Kelley** [comment]
Issue resolved from EW on our team.

Thank you for letting us know!
