### ISSUE TITLE
Please add ELLIO: IP Feed (Community version) to the feeds.

### ISSUE THREAD

**Issue by elliotechayush** [CriticalPathSecurity/Zeek-Intelligence-Feeds#31]
Hi,

First of all thanks for the awesome repo and the daily feed updates!

I was looking for a way to contribute in it too but couldn't find anything on that , so I think you can doing it only.
Please take a look at [https://cdn.ellio.tech/community-feed], I believe it will be a great addition to the Zeek-Intelligence Feeds.
Thank You.
More Info about Ellio Tech = https://ellio.tech
Let me know if you want to know anything else
Regards
Ayush Tomar.

**Comment by Patrick-Kelley** [comment]
Ayush Tomar,

Thank you for submitting the feed for the community! 

It has been added! I'll run some testing against it today, before I remove the "#". At that point, it will be live in all environments.

https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/master/ellio.intel

-PK

**Comment by elliotechayush** [comment]
Thank you so much for adding Ellio Community feed, but I think there is a minor issue. The link for both the home page and the list URL is same, can you please update the list URL link to https://feed.ellio.tech/ ?
Thank You
-Ayush

**Comment by Patrick-Kelley** [comment]
I'm updating the URL now. 

Thank you, Ayush!
