### ISSUE TITLE
missing "," in main.zeek

### ISSUE THREAD

**Issue by palichx** [CriticalPathSecurity/Zeek-Intelligence-Feeds#32]
Hi,
In the last version of the main.zeek(https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/master/main.zeek ) file, a "," is missing on line 24.

**Comment by Patrick-Kelley** [comment]
Thank you for notifying us! 

Updating now.

**Comment by palichx** [comment]
You're welcome!
