### ISSUE TITLE
invalid IP in zeek threat intel feed

### ISSUE THREAD

**Issue by mgcdeltarisk** [CriticalPathSecurity/Zeek-Intelligence-Feeds#33]
Hello, around ~5-6pm EST yesterday we started seeing an invalid IP address in the zeek threat intel feeds.  I've manually looked through the commits around that time but didn't find the offending entry.  I will continue to look and will update this issue once I've identified the culprit.  Thanks!

**Comment by CPS-Erin** [comment]
We'll look into this on our end as well. Thank you

**Comment by mgcdeltarisk** [comment]
I believe it's these two lines: https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/b8317fb4fa9a6e9380e148d1e079c918be704add/talos.intel#L1615 and https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/b8317fb4fa9a6e9380e148d1e079c918be704add/talos.intel#L1616

**Comment by CPS-Erin** [comment]
Acknowledged -- currently tracking upstream to see where the source is. Thank you for bringing this to our attention.

**Comment by CPS-Erin** [comment]
Modified parser. Please let us know if you continue to see issues. Thank you again for letting us know!

**Comment by mgcdeltarisk** [comment]
It looks good on our end now, thanks!
