### ISSUE TITLE
Invalid IP in tweetfeed.intel

### ISSUE THREAD

**Issue by mgcdeltarisk** [CriticalPathSecurity/Zeek-Intelligence-Feeds#34]
This IP has an invalid second octet:

https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/d92c74c44d3d86d2e2b524cfb12f7e4445c21b7a/tweetfeed.intel#L1305

Thanks!

**Comment by CPS-Erin** [comment]
Thank you for bringing this to our attention - we are looking into it.

**Comment by Patrick-Kelley** [comment]
I've altered the processing to filter any invalid octets from the source. 

It should be good going forward (for this feed, at least). I've dropped a ticket to work through the other feeds.

**Comment by mgcdeltarisk** [comment]
It looks like this one was removed and readded: https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/master/tweetfeed.intel#L1305

**Comment by Patrick-Kelley** [comment]
I see it. Working a solution now. 

Standby.

**Comment by Patrick-Kelley** [comment]
This should be properly sorted.
