### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by aziel12** [CriticalPathSecurity/Zeek-Intelligence-Feeds#5]
Hello, I have found www.amazon.com and www.youtube.com being flagged as cobaltstrike domains. Is it false positive? 
What does meta.do_notice mean, in all intel files they are F. Thanks
source in: cps_cobaltstrike_domain.intel

www.youtube.com	Intel::DOMAIN	CobaltStrike	F	C2
amazon.com	Intel::DOMAIN	CobaltStrike	F	C2

**Comment by Patrick-Kelley** [comment]
Apologies for just seeing this. 

Yes, the feed that included that artifact has a high-rate for false positives. I've commented out the line that spins it up. I'll work on a better solution in coming days.
