### ISSUE TITLE
cron entry in readme needs review.

### ISSUE THREAD

**Issue by mrc668** [CriticalPathSecurity/Zeek-Intelligence-Feeds#6]
The instructions you give in the README.md for the cron updates reads:
* 23 * * * do the update thing.
This will execute every minute between 23:00 and 00:00.

Hourly updates on the 23rd minute would look like:
23 * * * * foo bar baz.

**Comment by Patrick-Kelley** [comment]
You're absolutely right! I'm updating the README.md in this next push.

Thanks for calling it out.
