### ISSUE TITLE
log4j_ip.intel pulling in 0.0.0.0 and 1.1.1.1 cloudflare dns

### ISSUE THREAD

**Issue by glallen-cb** [CriticalPathSecurity/Zeek-Intelligence-Feeds#7]
https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/4fad0896f3b2996b3b4d59d3a1fcb82eeebca069/log4j_ip.intel#L2 0.0.0.0 and 1.1.1.1 jump out as potential false positives / unintended additions.

**Comment by Patrick-Kelley** [comment]
Yep. It was an upstream add. I’ll get an exclusion in there.

Patrick Kelley, CISSP, C|EH, ITIL
CTO
***@***.******@***.***>


On Dec 13, 2021, at 6:03 PM, glallen ***@***.***> wrote:

﻿

https://github.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/blob/4fad0896f3b2996b3b4d59d3a1fcb82eeebca069/log4j_ip.intel#L2 0.0.0.0 and 1.1.1.1 jump out as potential false positives / unintended additions.

**Comment by Patrick-Kelley** [comment]
As promised, I've built-in filtering for all no-routable addresses and have removed 0.0.0.0 and 1.1.1.1.

Unfortunately, this is an aggregation of community-data and the quality is based on that data. 

I'll do my best to keep it solid.
